[package]
name = "embedded-tz"
version = "0.1.3"
authors = [
    "kennytm <kennytm@gmail.com>",
    "Moshe Dicker <dickermoshe@gmail.com>",
]
edition = "2018"
description = "embedded/no_std chrono::TimeZone implementation for TZif data"
license = "MIT"
repository = "https://github.com/dickermoshe/embedded-tz"

[features]
bundled-tzdb = []

[dependencies]
byteorder = "1.3"
chrono = { version = "0.4.7", default-features = false }
heapless = { version = "0.9.2", features = ["portable-atomic"] }

[dev-dependencies]
lazy_static = "1.1"
criterion = "0.3"
chrono-tz = "0.10.4"
chrono = "0.4"
proptest = "1.10.0"
