[package]
name = "tzfile"
version = "0.1.3"
authors = ["kennytm <kennytm@gmail.com>"]
edition = "2018"
description = "chrono::TimeZone implementation using system tz database"
license = "MIT"
repository = "https://github.com/kennytm/tzfile"

[features]
bundled-tzdb = []

[dependencies]
byteorder = "1.3"
chrono = { version = "0.4.7", default-features = false }
heapless = { version = "0.9.2", features = ["portable-atomic"] }
paste = "1.0"

[dev-dependencies]
lazy_static = "1.1"
criterion = "0.3"
chrono-tz = "0.10.4"
chrono = "0.4"
proptest = "1.10.0"
